### ISSUE TITLE
Tune Tutorial: HyperOpt example crashes

### ISSUE THREAD

**Issue by vadimq** [ray-project/tutorial#100]
I use the latest stable version of Ray and the HyperOpt example raises the following exception:
`AttributeError: 'float' object has no attribute 'items'`

Found out that it doesn't occur if there is no `momentum` in the `config` of experiment2, but it would probably be better to fix the underlying issue (`deep_update` can't replace a dict with a non-dict).

**Comment by richardliaw** [comment]
Should be fixed.
