### ISSUE TITLE
Another plea to add check if initialized

### ISSUE THREAD

**Issue by endrebak** [ray-project/tutorial#119]
I have a usecase I find hard to solve with the ray API as it currently exists:

if users of my library have not initialized ray, I want to run in single-threaded mode, without using ray. Therefore I need to know whether ray has been initialized.

The current way I solve this is

```
if “ray” in sys.modules:
    try:
        # run dummy function with ray
        # to see if it throws not-init exception
        ray_initialized = True
    except:
        ray_initialized = True
```

Then I can do processing downstream based on this. But using try except is not as robust as it could be, and it is also verbose.

**Comment by robertnishihara** [comment]
@endrebak I think `ray.is_initialized()` does what you want! https://ray.readthedocs.io/en/latest/api.html#ray.is_initialized

**Comment by endrebak** [comment]
*Embarrased*. Sorry!
