### ISSUE TITLE
Batched wait

### ISSUE THREAD

**Issue by yifanwu** [ray-project/tutorial#16]
in exercise05.py, another alternative (harder) could be wait for either the first 10 or the last 10 (instead of any 10) --- would be a fun additional excercise

**Comment by robertnishihara** [comment]
I think that's what the exercise is asking for (or maybe I'm misunderstanding your comment). The exercise asks people to use `ray.wait` to wait for the first 10 that finish and then to get the remaining 10. Is that what you meant?

**Comment by yifanwu** [comment]
I think the exercise is _any_ first 10 (order defined at runtime), but my comment was on the first 10 in the array (order pre-defined).

**Comment by robertnishihara** [comment]
That makes sense. I'm closing this for now since the exercise seems to be working well as is.
