### ISSUE TITLE
minor tutorial bug

### ISSUE THREAD

**Issue by cbalaf-zz** [ray-project/tutorial#166]
in the very last cell of https://colab.research.google.com/github/ray-project/tutorial/blob/master/rllib_exercises/rllib_colab.ipynb, the last state (`max_state`) is used in the `np.mean` function instead of the list of states (`max_states`). Also, the print statement for the max state reached should probably have `np.max` instead of `np.mean`

**Comment by JiahaoYao** [comment]
Hi @cbalaf, this is not the bug. 
```
for i in range(5):
    state = env.reset()
    done = False
    max_state = -1
    cumulative_reward = 0
    while not done:
        action = trainer.compute_action(state)
        state, reward, done, results = env.step(action)
        max_state = max(max_state, state)
        cumulative_reward += reward
    max_states += [max_state]
```

the meaning of `max_state` is by `max_state = max(max_state, state)`. Then, `np.mean(max_state)` is just mean that we take the average for our five runs of the policy and get the average of the maximal state length.

**Comment by cbalaf-zz** [comment]
Right. I'm referring to
```
print("Cumulative reward you've received is: {}!".format(cumulative_reward))
print("Max state you've visited is: {}. This is out of {} states.".format(np.mean(max_state), env.n))
assert (env.n - np.mean(max_state)) / env.n < 0.2, "This policy did not traverse many states."
```

`max_state` is an integer, not a list, so you're only using the max state of the last run, not all of them. Also, presumably, the second print statement needs an `np.max` instead of `np.mean`

**Comment by JiahaoYao** [comment]
I see, you are right. I think I mean for the print statement, it should be `np.mean(max_states)`, where `max_states` is supposed to be the list. Here, taking the average is much better because considering the average situation not just the luckiest one.
