### ISSUE TITLE
minor tutorial typo

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/tutorial#168]
[https://colab.research.google.com/github/ray-project/tutorial/blob/master/exercises/colab06-07.ipynb](https://colab.research.google.com/github/ray-project/tutorial/blob/master/exercises/colab06-07.ipynb)
In the last **Exercise 7**, at the markdown
`results = ray.wait([f.remote(i) for i in range(100)], num_results=10)` should be changed to `num_returns` (instead of ~~`num_results`~~)

**Comment by richardliaw** [comment]
Can you make a pr?
