### ISSUE TITLE
Trouble installing TensorFlow (No matching distribution found for tensorflow==1.0).

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/tutorial#24]
Some people encountered the following problem when doing `pip install tensorflow` (with Anaconda).

```
Collecting tensorflow==1.0
  Could not find a version that satisfies the requirement tensorflow==1.0 (from versions: )
No matching distribution found for tensorflow==1.0
```

The solution may have been to install tensorflow with a URL like the following.

```
pip install --upgrade  https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.1.0-py2-none-any.whl
```

@richardliaw Is that correct? Do you remember what the solution was?

**Comment by richardliaw** [comment]
yep - that works for python2 installations.

**Comment by robertnishihara** [comment]
Ok great, thanks!

**Comment by crystalzyan** [comment]
For people with other installations, such as python3 or are on Ubuntu, I found this list of URLs for some other TensorFlow binaries:

​https://www.tensorflow.org/versions/r0.10/get_started/os_setup#pip_installation

Thus, if they had python3 on Mac OS X, they could use the command:

```
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0-py3-none-any.whl
```

**Comment by ghost** [comment]
thanks, excelllent

**Comment by najamrehman** [comment]
@crystalzyan Unable to install for python3 with error 
`pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)`

**Comment by robertnishihara** [comment]
@najamrehman can you provide more information about your OS, Python distribution, also include the exact command you are running and the full ouput?

**Comment by kumariabha** [comment]
nice, it is working, thank you

**Comment by juseph-dan** [comment]
Hi guys, please i need the link to install  Tensorflow for python v.3 on windows 
Thanks in Advance

**Comment by guptaabha** [comment]
https://www.blogger.com/blogger.g?blogID=8617062655904068083#editor/target=post;postID=4729958963785598234;onPublishedMenu=allposts;onClosedMenu=allposts;postNum=0;src=postname

**Comment by kumariabha** [comment]
@Mehdihym  this link may help you in installing Tensorflow in window
https://www.blogger.com/blogger.g?blogID=8617062655904068083#editor/target=post;postID=4729958963785598234;onPublishedMenu=allposts;onClosedMenu=allposts;postNum=0;src=postname

**Comment by juseph-dan** [comment]
@guptaabha Thanks 👍

**Comment by prayagupa** [comment]
Weird but I fixed the issue once got out of my corporate internet network.

```
pip3 install tensorflow
Collecting tensorflow
  Downloading https://files.pythonhosted.org/packages/64/6a/c0681f99098edc2ac32e7485ca5046cd47461b6ac379f65932c817913b34/tensorflow-1.7.0-cp36-cp36m-macosx_10_11_x86_64.whl (45.3MB)
    100% |████████████████████████████████| 45.3MB 29kB/s
```

**Comment by shivaniarbat** [comment]
thanks its working for me ! 👍

**Comment by adjouden** [comment]
I am getting a HTTP error 404- 
python3- Windows 10- when using pip install --upgrade  https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.1.0-py2-none-any.wh

**Comment by richardliaw** [comment]
Can you post on the Tensorflow issues or stackoverflow? TF installations are now a lot more stable, and people over there are probably better suited to answer your question/issues. I also believe `1.1.0` is just way too outdated for this to work anymore.

Thanks! (Also locking this conversation because out of date).
