### ISSUE TITLE
Run ERROR

### ISSUE THREAD

**Issue by aGiant** [ray-project/tutorial#53]
Hi,

when I ran the example like:
python evolution_strategies.py
I got
ImportError: No module named ray_tutorial.evolution_strategies

Where can I find the "ray_tutorial" library?

**Comment by robertnishihara** [comment]
I think I deleted that example from the tutorial repository a little while back. However, you can find the evolution strategies example in the main repository at https://github.com/ray-project/ray/tree/master/python/ray/rllib/es.

Some instructions here http://ray.readthedocs.io/en/latest/rllib.html.

**Comment by aGiant** [comment]
Change import:
from ray.rllib.es import (optimizers, policies, tabular_logger, tf_util, utils)
then got error:
AttributeError: 'module' object has no attribute 'MujocoPolicy'.
Can you give me a bugs-free example about ES using tensorflow-GPU? Thanks in advance

**Comment by robertnishihara** [comment]
If you install the latest version of Ray, clone the ray repository, and run

```
python ray/python/ray/rllib/train.py --alg=ES --env=CartPole-v0
```

That should work. ES currently doesn't benefit much from GPUs, but that's a modification that could be made.

**Comment by robertnishihara** [comment]
This exercise has been removed now.
