### ISSUE TITLE
Does the ray_tutorial.reinforce.agent.Agent train well??

### ISSUE THREAD

**Issue by ashigirl96** [ray-project/tutorial#58]
Thank you for your nice tutorial.

The `ray_tutorial.reinforce.agent.Agent` doesn't implement like `train()` method, so I override it as possible as I can.

But the loss didn't decrease. Please tell me which parts I have wrong?

https://github.com/ashigirl96/rl_snippets/blob/33499eee3eeefba5a299b3b7d35f29e116a9f349/experimental/use_tutorial_agent.py#L192-L220

**Comment by robertnishihara** [comment]
Hi, I think you're using code from an older version of the tutorial that has been removed. I'd suggest using the up-to-date code in RLlib http://ray.readthedocs.io/en/latest/rllib.html.

**Comment by ashigirl96** [comment]
Thank you for your prompt reply.
