### ISSUE TITLE
Excercise03 ray.get doesnot seem to wait for remote function completion

### ISSUE THREAD

**Issue by raghukoratagere** [ray-project/tutorial#81]
Modified code from Excercise3 is below:

@ray.remote
def compute_gradient(data):
    time.sleep(0.03)
    return 1

@ray.remote
def train_model(hyperparameters):
    result = 0
    for i in range(10):
        result += sum(ray.get([compute_gradient.remote(j) for j in range(2)]))
    return result

results = []
for hyperparameters in [{'learning_rate': 1e-1, 'batch_size': 100},
                        {'learning_rate': 1e-2, 'batch_size': 100},
                        {'learning_rate': 1e-3, 'batch_size': 100}]:
    results.append(train_model.remote(hyperparameters))

print(results)
ray.get(results) # This line is NOT  blocking ...
print(results)

end_time = time.time()
duration = end_time - start_time

===>
Output i see is below -

[ObjectID(80e4a9df518deab827ffee6ce9fde852ec326741), ObjectID(5f104cc60f425f5519c059dd72d24c9a100365a4), ObjectID(c95c5d3e4193a2bc764d27b07466ff2f6ae625b0)]

[ObjectID(80e4a9df518deab827ffee6ce9fde852ec326741), ObjectID(5f104cc60f425f5519c059dd72d24c9a100365a4), ObjectID(c95c5d3e4193a2bc764d27b07466ff2f6ae625b0)]

Seems like a bug somewhere. ray.get(results)  should have blocked the second print till the results array is resolved with actual function return values.

ray.get cannt retun ObjectIDs. As per documentation it should be: 

Returns: | A Python object or a list of Python objects.
--

Can some one comment.

**Comment by robertnishihara** [comment]
I think the issue is that the line `ray.get(results)` should actually be `results = ray.get(results)`.

**Comment by raghukoratagere** [comment]
Yes my bad. ray.get(results) does seem to be blocking just that missing assignment made me think it was not blocking. Thanks!
