### ISSUE TITLE
Excercise6 shows wait() got an unexpected keyword argument 'timeout_ms'

### ISSUE THREAD

**Issue by raghukoratagere** [ray-project/tutorial#82]
The code below -

initial_results = ray.wait(result_ids, num_returns=3, timeout_ms=None)

results in below erorr -
TypeError: wait() got an unexpected keyword argument 'timeout_ms'

without having timeout_ms cannt implement the excerise.

**Comment by raghukoratagere** [comment]
Looks like API signature has changed in 0.5.2 
ray.wait no more has 'timeout_ms' but has timeout and hence the error. May be the tutorial can suggest checking ray version before reporting error.

**Comment by robertnishihara** [comment]
You're right, thanks for pointing this out!
