### ISSUE TITLE
Exercise 7 typo

### ISSUE THREAD

**Issue by huitseeker** [ray-project/tutorial#88]
Exercise 7, penultimate cell:

```
    print('Processing result which finished after {} seconds.'
          .format(result - start_time))
```

the last should be `(time.Time() - start_time)`

**Comment by robertnishihara** [comment]
Ah, I think this is actually intentional, because `result` is returned from the remote function

```python
@ray.remote
def f():
    time.sleep(np.random.uniform(0, 5))
    return time.time()
```

which records the time when the function finished.

**Comment by huitseeker** [comment]
Fair enough — I seem to remember an exception at running this, but it may have been unrelated.
