### ISSUE TITLE
exercise 4 qeustion about loop

### ISSUE THREAD

**Issue by onlytailei** [ray-project/tutorial#97]
What's the difference for these two implementations of an actor?
```
for _ in range(5):
    results.append(f1.increment.remote())
results = ray.get(results)
```

```
results = ray.get([f1.increment.remote() for _ in range(5)])
````

The resuts are the same. But the first one is **too fast** for this problem?

**Comment by robertnishihara** [comment]
Those look identical to me. If the tutorial is saying that the first one is too fast, then the issue may be the placement of the timing statement. E.g., if the end time is being measured before the call to `ray.get`, that could make it appear too fast.

**Comment by onlytailei** [comment]
Oh thanks! you are right!
