### ISSUE TITLE
[Request] More low-level examples on RLlib

### ISSUE THREAD

**Issue by jpiabrantes** [ray-project/tutorial#98]
I am trying to learn how to use RLlib default models/optimisers/environments but also how to create my own and add them to RLlib. I would like to see an example (could be the PPO with Cartpole) being built from scratch step by step - when I look into the code and see it whole at once I get a bit overwhelmed. Was this already done somewhere else?

Love what you have been building! Cheers.

**Comment by ericl** [comment]
Hey @jpiabrantes , you might want to look at the policy gradient example, it's a minimal PG implementation that still works with all the rllib features.

https://github.com/ray-project/ray/tree/master/python/ray/rllib/agents/pg

**Comment by jpiabrantes** [comment]
Thanks @ericl that helped!
